In [4]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [5]:
df=pd.read_csv('qoute_dataset.csv')

In [6]:
df.head()

                                               quote           Author
0  “The world as we have created it is a process ...  Albert Einstein
1  “It is our choices, Harry, that show what we t...     J.K. Rowling
2  “There are only two ways to live your life. On...  Albert Einstein
3  “The person, be it gentleman or lady, who has ...      Jane Austen
4  “Imperfection is beauty, madness is genius and...   Marilyn Monroe

In [39]:
df.shape

(3038, 2)

In [40]:
quotes=df['quote']
quotes.head()

0    “The world as we have created it is a process ...
1    “It is our choices, Harry, that show what we t...
2    “There are only two ways to live your life. On...
3    “The person, be it gentleman or lady, who has ...
4    “Imperfection is beauty, madness is genius and...
Name: quote, dtype: object

In [41]:
quotes=quotes.str.lower()

In [42]:
import string
translator=str.maketrans('','',string.punctuation)
quotes = quotes.apply(lambda x : x.translate(translator))

In [43]:
quotes.head()

0    “the world as we have created it is a process ...
1    “it is our choices harry that show what we tru...
2    “there are only two ways to live your life one...
3    “the person be it gentleman or lady who has no...
4    “imperfection is beauty madness is genius and ...
Name: quote, dtype: object

In [44]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [45]:
vocab_size=8978

In [46]:
tok=Tokenizer(num_words=vocab_size)
tok.fit_on_texts(quotes)

In [47]:
tok.index_word

{1: 'the',
 2: 'you',
 3: 'to',
 4: 'and',
 5: 'a',
 6: 'i',
 7: 'is',
 8: 'of',
 9: 'that',
 10: 'it',
 11: 'in',
 12: 'be',
 13: 'not',
 14: 'are',
 15: 'your',
 16: 'have',
 17: 'for',
 18: 'but',
 19: 'we',
 20: 'if',
 21: 'what',
 22: 'with',
 23: 'all',
 24: 'love',
 25: 'can',
 26: 'my',
 27: 'when',
 28: 'will',
 29: 'as',
 30: 'who',
 31: 'do',
 32: 'or',
 33: 'me',
 34: 'he',
 35: 'they',
 36: 'life',
 37: 'one',
 38: 'was',
 39: 'like',
 40: 'there',
 41: 'people',
 42: 'on',
 43: 'its',
 44: 'at',
 45: 'so',
 46: 'never',
 47: 'no',
 48: 'them',
 49: 'dont',
 50: 'know',
 51: 'just',
 52: 'more',
 53: 'only',
 54: 'than',
 55: 'because',
 56: 'this',
 57: 'want',
 58: 'up',
 59: 'how',
 60: 'his',
 61: 'things',
 62: 'world',
 63: 'by',
 64: 'think',
 65: 'make',
 66: 'about',
 67: 'time',
 68: 'from',
 69: 'always',
 70: 'our',
 71: 'an',
 72: 'out',
 73: 'us',
 74: 'good',
 75: 'said',
 76: 'she',
 77: 'her',
 78: 'way',
 79: 'go',
 80: 'am',
 81: 'live',
 82: 'has',
 83: 'something',
 84: 'see',
 85: 'too',
 86: 'then',
 87: 'every',
 88: 'were',
 89: 'some',
 90: 'man',
 91: 'thing',
 92: 'heart',
 93: 'nothing',
 94: 'get',
 95: 'him',
 96: 'youre',
 97: 'would',
 98: 'those',
 99: 'their',
 100: 'yourself',
 101: 'other',
 102: 'let',
 103: 'into',
 104: 'without',
 105: 'much',
 106: 'im',
 107: 'could',
 108: 'had',
 109: 'someone',
 110: 'ever',
 111: 'day',
 112: 'even',
 113: 'find',
 114: 'books',
 115: 'right',
 116: 'person',
 117: 'most',
 118: 'say',
 119: 'must',
 120: 'which',
 121: 'been',
 122: 'own',
 123: 'sometimes',
 124: 'read',
 125: 'should',
 126: 'everything',
 127: 'believe',
 128: 'being',
 129: 'really',
 130: 'going',
 131: 'feel',
 132: 'come',
 133: 'give',
 134: 'may',
 135: 'where',
 136: 'book',
 137: 'thats',
 138: 'tell',
 139: 'little',
 140: 'cant',
 141: 'back',
 142: 'words',
 143: 'over',
 144: 'better',
 145: 'cannot',
 146: 'through',
 147: 'now',
 148: 'any',
 149: 'enough',
 150: 'does',
 151: 'great',
 152: 'god',
 153: 'look',
 154: 'anything',
 155: 'change',
 156: 'another',
 157: 'many',
 158: 'remember',
 159: 'best',
 160: 'down',
 161: 'true',
 162: 'still',
 163: 'did',
 164: 'need',
 165: 'mind',
 166: 'soul',
 167: 'well',
 168: 'until',
 169: 'each',
 170: 'again',
 171: 'else',
 172: 'why',
 173: 'long',
 174: 'truth',
 175: 'loved',
 176: 'keep',
 177: 'very',
 178: 'first',
 179: 'moment',
 180: 'woman',
 181: 'matter',
 182: 'doesnt',
 183: 'before',
 184: 'men',
 185: 'others',
 186: 'once',
 187: 'human',
 188: 'fear',
 189: 'end',
 190: 'around',
 191: 'ive',
 192: 'beautiful',
 193: 'happy',
 194: 'kind',
 195: 'don’t',
 196: 'die',
 197: 'girl',
 198: 'happiness',
 199: 'made',
 200: 'take',
 201: 'two',
 202: 'become',
 203: 'learn',
 204: 'myself',
 205: 'theres',
 206: 'got',
 207: 'hope',
 208: 'part',
 209: 'same',
 210: 'alone',
 211: 'pain',
 212: 'friends',
 213: 'makes',
 214: 'death',
 215: 'real',
 216: 'friend',
 217: 'inside',
 218: 'thought',
 219: 'after',
 220: 'years',
 221: 'here',
 222: 'eyes',
 223: 'wrong',
 224: 'understand',
 225: 'loves',
 226: 'lives',
 227: 'reading',
 228: 'fall',
 229: 'new',
 230: 'light',
 231: 'forever',
 232: 'while',
 233: 'dream',
 234: 'ones',
 235: 'everyone',
 236: 'living',
 237: 'youll',
 238: 'bad',
 239: 'lose',
 240: 'away',
 241: 'forget',
 242: 'shall',
 243: 'hard',
 244: 'upon',
 245: 'between',
 246: 'face',
 247: 'stop',
 248: 'write',
 249: 'dreams',
 250: 'off',
 251: 'future',
 252: 'whole',
 253: 'might',
 254: 'maybe',
 255: 'ourselves',
 256: 'hell',
 257: 'looking',
 258: 'stars',
 259: 'wanted',
 260: 'trying',
 261: 'old',
 262: 'last',
 263: 'isnt',
 264: 'courage',
 265: 'try',
 266: 'mean',
 267: 'together',
 268: 'doing',
 269: 'place',
 270: 'less',
 271: 'stay',
 272: 'theyre',
 273: 'hate',
 274: 'knows',
 275: 'earth',
 276: 'put',
 277: 'felt',
 278: 'times',
 279: 'rather',
 280: 'often',
 281: 'work',
 282: 'night',
 283: 'trust',
 284: 'grow',
 285: 'walk',
 286: 'says',
 287: 'saying',
 288: 'anyone',
 289: 'smile',
 290: 'hurt',
 291: 'story',
 292: 'listen',
 293: 'thinking',
 294: 'far',
 295: 'laugh',
 296: 'small',
 297: 'having',
 298: 'reality',
 299: 'means',
 300: 'women',
 301: 'sad',
 302: 'leave',
 303: 'these',
 304: 'head',
 305: 'music',
 306: 'i’m',
 307: 'youve',
 308: 'it’s',
 309: 'important',
 310: 'somebody',
 311: 'against',
 312: 'feeling',
 313: 'beauty',
 314: 'stand',
 315: 'hand',
 316: 'done',
 317: 'reason',
 318: 'universe',
 319: 'didnt',
 320: 'fire',
 321: 'told',
 322: 'strong',
 323: 'happens',
 324: 'sure',
 325: 'talk',
 326: 'word',
 327: 'himself',
 328: 'full',
 329: 'though',
 330: 'gone',
 331: 'worth',
 332: 'point',
 333: 'door',
 334: 'broken',
 335: 'dark',
 336: 'sit',
 337: 'wish',
 338: 'happen',
 339: 'you’re',
 340: 'least',
 341: 'past',
 342: 'comes',
 343: 'hold',
 344: 'takes',
 345: 'perfect',
 346: 'stupid',
 347: 'children',
 348: 'start',
 349: 'experience',
 350: 'power',
 351: 'yet',
 352: 'asked',
 353: 'realize',
 354: 'making',
 355: 'behind',
 356: 'left',
 357: 'wants',
 358: 'choose',
 359: 'lot',
 360: 'whatever',
 361: 'lost',
 362: 'looked',
 363: 'wont',
 364: 'knowing',
 365: 'few',
 366: 'lie',
 367: 'different',
 368: 'hear',
 369: 'afraid',
 370: 'jace',
 371: 'ask',
 372: 'home',
 373: 'harry',
 374: 'impossible',
 375: 'lies',
 376: 'open',
 377: 'easy',
 378: 'already',
 379: 'three',
 380: 'exist',
 381: 'such',
 382: 'possible',
 383: 'use',
 384: 'thoughts',
 385: 'within',
 386: 'days',
 387: '—',
 388: 'themselves',
 389: 'also',
 390: 'break',
 391: 'mistakes',
 392: 'loving',
 393: 'alive',
 394: 'next',
 395: 'happened',
 396: 'wait',
 397: 'side',
 398: 'both',
 399: 'ill',
 400: 'secret',
 401: 'deep',
 402: 'sleep',
 403: 'silence',
 404: 'either',
 405: 'suffering',
 406: 'tomorrow',
 407: 'call',
 408: 'strength',
 409: 'help',
 410: 'meant',
 411: 'knew',
 412: 'speak',
 413: 'itself',
 414: 'seen',
 415: 'found',
 416: 'pretty',
 417: 'half',
 418: 'goes',
 419: 'high',
 420: 'lived',
 421: 'darkness',
 422: 'yours',
 423: 'choice',
 424: 'forgive',
 425: 'respect',
 426: 'young',
 427: 'simple',
 428: 'close',
 429: 'kill',
 430: 'beginning',
 431: 'whats',
 432: 'perhaps',
 433: 'show',
 434: 'success',
 435: 'arent',
 436: 'mad',
 437: 'friendship',
 438: 'thousand',
 439: 'crazy',
 440: 'house',
 441: 'nobody',
 442: 'history',
 443: 'able',
 444: 'set',
 445: 'meet',
 446: 'hands',
 447: 'rest',
 448: 'answer',
 449: 'id',
 450: 'voice',
 451: 'dare',
 452: 'second',
 453: 'expect',
 454: 'war',
 455: 'free',
 456: 'room',
 457: 'seems',
 458: 'somewhere',
 459: 'care',
 460: 'couldnt',
 461: 'fight',
 462: 'known',
 463: 'lonely',
 464: 'family',
 465: 'truly',
 466: 'decide',
 467: 'year',
 468: 'black',
 469: 'unless',
 470: 'begin',
 471: 'turn',
 472: 'sun',
 473: 'body',
 474: 'today',
 475: 'enjoy',
 476: 'child',
 477: 'fact',
 478: 'worse',
 479: 'yes',
 480: 'freedom',
 481: 'mother',
 482: 'actually',
 483: 'course',
 484: 'born',
 485: 'seem',
 486: 'difference',
 487: 'dead',
 488: 'taste',
 489: 'everybody',
 490: 'peace',
 491: 'took',
 492: '–',
 493: 'stories',
 494: 'loneliness',
 495: 'art',
 496: 'imagination',
 497: 'wise',
 498: 'big',
 499: 'question',
 500: 'boy',
 501: 'learned',
 502: 'single',
 503: 'completely',
 504: 'water',
 505: 'knowledge',
 506: 'gives',
 507: 'hes',
 508: 'wisdom',
 509: 'desire',
 510: 'carry',
 511: 'gets',
 512: 'sea',
 513: 'waste',
 514: 'bear',
 515: 'father',
 516: 'girls',
 517: 'act',
 518: 'fool',
 519: 'persons',
 520: 'control',
 521: 'finally',
 522: 'apart',
 523: 'special',
 524: 'quite',
 525: 'stronger',
 526: 'imagine',
 527: 'name',
 528: 'hurts',
 529: 'minds',
 530: 'under',
 531: 'teach',
 532: 'school',
 533: 'nice',
 534: 'touch',
 535: 'wake',
 536: 'tree',
 537: 'morning',
 538: 'mine',
 539: 'ten',
 540: 'called',
 541: 'came',
 542: 'seek',
 543: 'weve',
 544: 'sense',
 545: 'getting',
 546: 'kiss',
 547: 'writing',
 548: 'needs',
 549: 'deserve',
 550: 'dance',
 551: 'front',
 552: 'greatest',
 553: 'memories',
 554: 'sky',
 555: 'joy',
 556: 'feet',
 557: 'used',
 558: 'nor',
 559: 'value',
 560: 'age',
 561: 'longer',
 562: 'wouldnt',
 563: 'certain',
 564: 'okay',
 565: 'spend',
 566: 'run',
 567: 'clary',
 568: 'arms',
 569: 'merely',
 570: 'hearts',
 571: 'blood',
 572: 'short',
 573: 'met',
 574: 'shes',
 575: 'miss',
 576: 'simply',
 577: 'thinks',
 578: 'intelligent',
 579: 'oh',
 580: 'wrote',
 581: 'brave',
 582: 'whom',
 583: 'written',
 584: 'can’t',
 585: 'cry',
 586: 'feelings',
 587: 'storm',
 588: 'anybody',
 589: 'poetry',
 590: 'wonder',
 591: 'powerful',
 592: 'magic',
 593: 'gave',
 594: 'guy',
 595: 'step',
 596: 'burn',
 597: 'moon',
 598: 'escape',
 599: 'passion',
 600: 'trees',
 601: 'pleasure',
 602: 'matters',
 603: 'fantasy',
 604: 'necessary',
 605: 'faith',
 606: 'late',
 607: 'leaves',
 608: 'drink',
 609: 'avoid',
 610: 'above',
 611: 'heard',
 612: 'along',
 613: 'travel',
 614: 'infinite',
 615: 'throw',
 616: 'library',
 617: 'questions',
 618: 'looks',
 619: 'usually',
 620: 'holding',
 621: 'youd',
 622: 'instead',
 623: 'poor',
 624: 'memory',
 625: 'hour',
 626: 'grief',
 627: 'meaning',
 628: 'becomes',
 629: 'hide',
 630: 'saw',
 631: 'weak',
 632: 'falling',
 633: 'sex',
 634: 'almost',
 635: 'play',
 636: 'shut',
 637: 'cool',
 638: 'genius',
 639: 'hot',
 640: 'deal',
 641: 'minute',
 642: 'places',
 643: 'dies',
 644: 'probably',
 645: 'coming',
 646: 'painful',
 647: 'skin',
 648: 'heaven',
 649: 'accept',
 650: 'you’ve',
 651: 'build',
 652: 'song',
 653: 'laughter',
 654: 'didn’t',
 655: 'bring',
 656: 'wind',
 657: 'remain',
 658: 'none',
 659: 'common',
 660: 'move',
 661: 'nature',
 662: 'purpose',
 663: 'money',
 664: 'waiting',
 665: 'except',
 666: 'air',
 667: 'kids',
 668: 'beyond',
 669: 'losing',
 670: 'middle',
 671: 'evil',
 672: 'tears',
 673: 'follow',
 674: 'running',
 675: 'went',
 676: 'sweet',
 677: 'bed',
 678: 'gods',
 679: 'they’re',
 680: 'لا',
 681: 'و',
 682: 'absolutely',
 683: 'fail',
 684: 'asleep',
 685: 'fairy',
 686: 'tales',
 687: 'large',
 688: 'angel',
 689: 'ready',
 690: 'tried',
 691: 'therefore',
 692: 'worst',
 693: 'mans',
 694: 'forward',
 695: 'wonderful',
 696: 'worry',
 697: 'that’s',
 698: 'present',
 699: 'forgotten',
 700: 'space',
 701: 'dying',
 702: 'whether',
 703: 'rain',
 704: 'amazing',
 705: 'road',
 706: 'count',
 707: 'kindness',
 708: 'eat',
 709: 'wasnt',
 710: 'white',
 711: 'reach',
 712: 'mouth',
 713: '“the',
 714: 'ways',
 715: '“i',
 716: 'judge',
 717: 'eye',
 718: 'sin',
 719: 'soon',
 720: 'spirit',
 721: 'across',
 722: 'lord',
 723: 'terrible',
 724: 'taken',
 725: 'silent',
 726: 'outside',
 727: 'greater',
 728: 'idea',
 729: 'humans',
 730: 'moving',
 731: 'hours',
 732: 'strange',
 733: 'education',
 734: 'sight',
 735: 'learning',
 736: 'sing',
 737: 'begins',
 738: 'fun',
 739: 'fighting',
 740: 'religion',
 741: 'form',
 742: 'paper',
 743: 'crying',
 744: 'piece',
 745: 'window',
 746: 'among',
 747: 'leaving',
 748: 'cut',
 749: 'toward',
 750: 'moments',
 751: 'songs',
 752: 'changing',
 753: 'madness',
 754: 'mess',
 755: 'enemies',
 756: 'needed',
 757: 'unhappy',
 758: 'chest',
 759: 'angry',
 760: 'problem',
 761: 'order',
 762: 'safe',
 763: 'troubles',
 764: 'trouble',
 765: 'whenever',
 766: 'someday',
 767: 'mistake',
 768: 'path',
 769: 'difficult',
 770: 'discover',
 771: 'share',
 772: 'blue',
 773: 'fell',
 774: 'please',
 775: 'interesting',
 776: 'figure',
 777: 'failure',
 778: 'hundred',
 779: 'wounds',
 780: 'given',
 781: 'fly',
 782: 'turned',
 783: 'pretend',
 784: 'telling',
 785: 'giving',
 786: 'stood',
 787: 'watch',
 788: 'glass',
 789: 'summer',
 790: 'hates',
 791: 'food',
 792: 'lips',
 793: 'protect',
 794: 'started',
 795: 'havent',
 796: 'ability',
 797: 'easier',
 798: 'ideas',
 799: 'rare',
 800: 'kissed',
 801: 'fill',
 802: 'opinion',
 803: 'instant',
 804: 'soft',
 805: 'depends',
 806: 'هو',
 807: 'sort',
 808: 'أن',
 809: 'changed',
 810: 'tea',
 811: 'anyway',
 812: 'baby',
 813: 'smiling',
 814: 'brain',
 815: 'opposite',
 816: 'indifference',
 817: 'problems',
 818: 'case',
 819: 'cup',
 820: 'attempt',
 821: 'doubt',
 822: 'ahead',
 823: 'flower',
 824: 'characters',
 825: 'rules',
 826: 'chance',
 827: 'boring',
 828: 'dragons',
 829: 'risk',
 830: 'gift',
 831: 'deeply',
 832: 'adventure',
 833: 'walls',
 834: 'guess',
 835: 'clothes',
 836: 'glory',
 837: 'taught',
 838: 'he’s',
 839: 'bird',
 840: 'fig',
 841: 'wear',
 842: 'destroy',
 843: 'actions',
 844: 'magnus',
 845: 'floor',
 846: 'hair',
 847: 'survive',
 848: 'fingers',
 849: 'force',
 850: 'ron',
 851: 'goodbye',
 852: 'rule',
 853: 'families',
 854: 'understanding',
 855: 'self',
 856: 'capable',
 857: 'fox',
 858: 'stuff',
 859: 'herself',
 860: 'burning',
 861: 'spring',
 862: 'naked',
 863: 'sorrow',
 864: 'doesn’t',
 865: 'country',
 866: 'wanting',
 867: 'talking',
 868: 'tells',
 869: 'من',
 870: 'chamber',
 871: 'choices',
 872: 'lifes',
 873: 'bravery',
 874: 'nonsense',
 875: 'lack',
 876: 'conscience',
 877: 'pride',
 878: 'reader',
 879: 'reads',
 880: 'lover',
 881: 'horrible',
 882: 'belief',
 883: 'fully',
 884: 'dumbledore',
 885: 'constantly',
 886: 'kept',
 887: 'allow',
 888: 'gold',
 889: 'car',
 890: 'cats',
 891: 'blind',
 892: 'bit',
 893: 'bigger',
 894: 'you’ll',
 895: 'sound',
 896: '2',
 897: 'deepest',
 898: 'warm',
 899: 'writer',
 900: 'greatness',
 901: 'science',
 902: 'character',
 903: 'believed',
 904: 'lucky',
 905: 'awful',
 906: 'job',
 907: 'sorry',
 908: 'hidden',
 909: 'cold',
 910: 'opinions',
 911: 'easily',
 912: 'somehow',
 913: 'complete',
 914: 'relationship',
 915: 'surprise',
 916: 'wed',
 917: 'dangerous',
 918: 'promise',
 919: 'precisely',
 920: 'realized',
 921: 'offer',
 922: 'create',
 923: 'empty',
 924: 'wild',
 925: 'sadness',
 926: 'lets',
 927: 'neither',
 928: 'hit',
 929: 'killed',
 930: 'peeta',
 931: 'i’ve',
 932: 'enemy',
 933: 'feels',
 934: 'tired',
 935: 'teacher',
 936: 'corner',
 937: 'flowers',
 938: 'missing',
 939: 'parents',
 940: 'return',
 941: 'comfort',
 942: 'suddenly',
 943: 'depression',
 944: 'eternal',
 945: 'نصف',
 946: 'created',
 947: '“it',
 948: 'theyll',
 949: 'explain',
 950: 'six',
 951: 'cause',
 952: 'admit',
 953: 'onto',
 954: 'sitting',
 955: 'happening',
 956: 'staring',
 957: 'opened',
 958: 'possibly',
 959: 'whose',
 960: 'answers',
 961: 'drive',
 962: 'differently',
 963: 'ignore',
 964: 'quiet',
 965: 'clear',
 966: 'brings',
 967: 'mate',
 968: 'yesterday',
 969: 'till',
 970: 'dogs',
 971: 'dust',
 972: 'fallen',
 973: 'lead',
 974: 'fit',
 975: 'transform',
 976: 'tessa',
 977: 'pretending',
 978: 'taking',
 979: 'date',
 980: 'list',
 981: 'she’s',
 982: 'pages',
 983: 'likes',
 984: 'understood',
 985: 'favorite',
 986: 'breath',
 987: 'pure',
 988: 'filled',
 989: 'scars',
 990: 'ordinary',
 991: 'grateful',
 992: 'literature',
 993: 'sees',
 994: 'advice',
 995: 'parts',
 996: 'simon',
 997: 'faster',
 998: 'fine',
 999: 'fate',
 1000: 'ugly',
 ...}

In [48]:
len(tok.index_word)

8978

In [49]:
tok.index_word

{1: 'the',
 2: 'you',
 3: 'to',
 4: 'and',
 5: 'a',
 6: 'i',
 7: 'is',
 8: 'of',
 9: 'that',
 10: 'it',
 11: 'in',
 12: 'be',
 13: 'not',
 14: 'are',
 15: 'your',
 16: 'have',
 17: 'for',
 18: 'but',
 19: 'we',
 20: 'if',
 21: 'what',
 22: 'with',
 23: 'all',
 24: 'love',
 25: 'can',
 26: 'my',
 27: 'when',
 28: 'will',
 29: 'as',
 30: 'who',
 31: 'do',
 32: 'or',
 33: 'me',
 34: 'he',
 35: 'they',
 36: 'life',
 37: 'one',
 38: 'was',
 39: 'like',
 40: 'there',
 41: 'people',
 42: 'on',
 43: 'its',
 44: 'at',
 45: 'so',
 46: 'never',
 47: 'no',
 48: 'them',
 49: 'dont',
 50: 'know',
 51: 'just',
 52: 'more',
 53: 'only',
 54: 'than',
 55: 'because',
 56: 'this',
 57: 'want',
 58: 'up',
 59: 'how',
 60: 'his',
 61: 'things',
 62: 'world',
 63: 'by',
 64: 'think',
 65: 'make',
 66: 'about',
 67: 'time',
 68: 'from',
 69: 'always',
 70: 'our',
 71: 'an',
 72: 'out',
 73: 'us',
 74: 'good',
 75: 'said',
 76: 'she',
 77: 'her',
 78: 'way',
 79: 'go',
 80: 'am',
 81: 'live',
 82: 'has',
 83: 'something',
 84: 'see',
 85: 'too',
 86: 'then',
 87: 'every',
 88: 'were',
 89: 'some',
 90: 'man',
 91: 'thing',
 92: 'heart',
 93: 'nothing',
 94: 'get',
 95: 'him',
 96: 'youre',
 97: 'would',
 98: 'those',
 99: 'their',
 100: 'yourself',
 101: 'other',
 102: 'let',
 103: 'into',
 104: 'without',
 105: 'much',
 106: 'im',
 107: 'could',
 108: 'had',
 109: 'someone',
 110: 'ever',
 111: 'day',
 112: 'even',
 113: 'find',
 114: 'books',
 115: 'right',
 116: 'person',
 117: 'most',
 118: 'say',
 119: 'must',
 120: 'which',
 121: 'been',
 122: 'own',
 123: 'sometimes',
 124: 'read',
 125: 'should',
 126: 'everything',
 127: 'believe',
 128: 'being',
 129: 'really',
 130: 'going',
 131: 'feel',
 132: 'come',
 133: 'give',
 134: 'may',
 135: 'where',
 136: 'book',
 137: 'thats',
 138: 'tell',
 139: 'little',
 140: 'cant',
 141: 'back',
 142: 'words',
 143: 'over',
 144: 'better',
 145: 'cannot',
 146: 'through',
 147: 'now',
 148: 'any',
 149: 'enough',
 150: 'does',
 151: 'great',
 152: 'god',
 153: 'look',
 154: 'anything',
 155: 'change',
 156: 'another',
 157: 'many',
 158: 'remember',
 159: 'best',
 160: 'down',
 161: 'true',
 162: 'still',
 163: 'did',
 164: 'need',
 165: 'mind',
 166: 'soul',
 167: 'well',
 168: 'until',
 169: 'each',
 170: 'again',
 171: 'else',
 172: 'why',
 173: 'long',
 174: 'truth',
 175: 'loved',
 176: 'keep',
 177: 'very',
 178: 'first',
 179: 'moment',
 180: 'woman',
 181: 'matter',
 182: 'doesnt',
 183: 'before',
 184: 'men',
 185: 'others',
 186: 'once',
 187: 'human',
 188: 'fear',
 189: 'end',
 190: 'around',
 191: 'ive',
 192: 'beautiful',
 193: 'happy',
 194: 'kind',
 195: 'don’t',
 196: 'die',
 197: 'girl',
 198: 'happiness',
 199: 'made',
 200: 'take',
 201: 'two',
 202: 'become',
 203: 'learn',
 204: 'myself',
 205: 'theres',
 206: 'got',
 207: 'hope',
 208: 'part',
 209: 'same',
 210: 'alone',
 211: 'pain',
 212: 'friends',
 213: 'makes',
 214: 'death',
 215: 'real',
 216: 'friend',
 217: 'inside',
 218: 'thought',
 219: 'after',
 220: 'years',
 221: 'here',
 222: 'eyes',
 223: 'wrong',
 224: 'understand',
 225: 'loves',
 226: 'lives',
 227: 'reading',
 228: 'fall',
 229: 'new',
 230: 'light',
 231: 'forever',
 232: 'while',
 233: 'dream',
 234: 'ones',
 235: 'everyone',
 236: 'living',
 237: 'youll',
 238: 'bad',
 239: 'lose',
 240: 'away',
 241: 'forget',
 242: 'shall',
 243: 'hard',
 244: 'upon',
 245: 'between',
 246: 'face',
 247: 'stop',
 248: 'write',
 249: 'dreams',
 250: 'off',
 251: 'future',
 252: 'whole',
 253: 'might',
 254: 'maybe',
 255: 'ourselves',
 256: 'hell',
 257: 'looking',
 258: 'stars',
 259: 'wanted',
 260: 'trying',
 261: 'old',
 262: 'last',
 263: 'isnt',
 264: 'courage',
 265: 'try',
 266: 'mean',
 267: 'together',
 268: 'doing',
 269: 'place',
 270: 'less',
 271: 'stay',
 272: 'theyre',
 273: 'hate',
 274: 'knows',
 275: 'earth',
 276: 'put',
 277: 'felt',
 278: 'times',
 279: 'rather',
 280: 'often',
 281: 'work',
 282: 'night',
 283: 'trust',
 284: 'grow',
 285: 'walk',
 286: 'says',
 287: 'saying',
 288: 'anyone',
 289: 'smile',
 290: 'hurt',
 291: 'story',
 292: 'listen',
 293: 'thinking',
 294: 'far',
 295: 'laugh',
 296: 'small',
 297: 'having',
 298: 'reality',
 299: 'means',
 300: 'women',
 301: 'sad',
 302: 'leave',
 303: 'these',
 304: 'head',
 305: 'music',
 306: 'i’m',
 307: 'youve',
 308: 'it’s',
 309: 'important',
 310: 'somebody',
 311: 'against',
 312: 'feeling',
 313: 'beauty',
 314: 'stand',
 315: 'hand',
 316: 'done',
 317: 'reason',
 318: 'universe',
 319: 'didnt',
 320: 'fire',
 321: 'told',
 322: 'strong',
 323: 'happens',
 324: 'sure',
 325: 'talk',
 326: 'word',
 327: 'himself',
 328: 'full',
 329: 'though',
 330: 'gone',
 331: 'worth',
 332: 'point',
 333: 'door',
 334: 'broken',
 335: 'dark',
 336: 'sit',
 337: 'wish',
 338: 'happen',
 339: 'you’re',
 340: 'least',
 341: 'past',
 342: 'comes',
 343: 'hold',
 344: 'takes',
 345: 'perfect',
 346: 'stupid',
 347: 'children',
 348: 'start',
 349: 'experience',
 350: 'power',
 351: 'yet',
 352: 'asked',
 353: 'realize',
 354: 'making',
 355: 'behind',
 356: 'left',
 357: 'wants',
 358: 'choose',
 359: 'lot',
 360: 'whatever',
 361: 'lost',
 362: 'looked',
 363: 'wont',
 364: 'knowing',
 365: 'few',
 366: 'lie',
 367: 'different',
 368: 'hear',
 369: 'afraid',
 370: 'jace',
 371: 'ask',
 372: 'home',
 373: 'harry',
 374: 'impossible',
 375: 'lies',
 376: 'open',
 377: 'easy',
 378: 'already',
 379: 'three',
 380: 'exist',
 381: 'such',
 382: 'possible',
 383: 'use',
 384: 'thoughts',
 385: 'within',
 386: 'days',
 387: '—',
 388: 'themselves',
 389: 'also',
 390: 'break',
 391: 'mistakes',
 392: 'loving',
 393: 'alive',
 394: 'next',
 395: 'happened',
 396: 'wait',
 397: 'side',
 398: 'both',
 399: 'ill',
 400: 'secret',
 401: 'deep',
 402: 'sleep',
 403: 'silence',
 404: 'either',
 405: 'suffering',
 406: 'tomorrow',
 407: 'call',
 408: 'strength',
 409: 'help',
 410: 'meant',
 411: 'knew',
 412: 'speak',
 413: 'itself',
 414: 'seen',
 415: 'found',
 416: 'pretty',
 417: 'half',
 418: 'goes',
 419: 'high',
 420: 'lived',
 421: 'darkness',
 422: 'yours',
 423: 'choice',
 424: 'forgive',
 425: 'respect',
 426: 'young',
 427: 'simple',
 428: 'close',
 429: 'kill',
 430: 'beginning',
 431: 'whats',
 432: 'perhaps',
 433: 'show',
 434: 'success',
 435: 'arent',
 436: 'mad',
 437: 'friendship',
 438: 'thousand',
 439: 'crazy',
 440: 'house',
 441: 'nobody',
 442: 'history',
 443: 'able',
 444: 'set',
 445: 'meet',
 446: 'hands',
 447: 'rest',
 448: 'answer',
 449: 'id',
 450: 'voice',
 451: 'dare',
 452: 'second',
 453: 'expect',
 454: 'war',
 455: 'free',
 456: 'room',
 457: 'seems',
 458: 'somewhere',
 459: 'care',
 460: 'couldnt',
 461: 'fight',
 462: 'known',
 463: 'lonely',
 464: 'family',
 465: 'truly',
 466: 'decide',
 467: 'year',
 468: 'black',
 469: 'unless',
 470: 'begin',
 471: 'turn',
 472: 'sun',
 473: 'body',
 474: 'today',
 475: 'enjoy',
 476: 'child',
 477: 'fact',
 478: 'worse',
 479: 'yes',
 480: 'freedom',
 481: 'mother',
 482: 'actually',
 483: 'course',
 484: 'born',
 485: 'seem',
 486: 'difference',
 487: 'dead',
 488: 'taste',
 489: 'everybody',
 490: 'peace',
 491: 'took',
 492: '–',
 493: 'stories',
 494: 'loneliness',
 495: 'art',
 496: 'imagination',
 497: 'wise',
 498: 'big',
 499: 'question',
 500: 'boy',
 501: 'learned',
 502: 'single',
 503: 'completely',
 504: 'water',
 505: 'knowledge',
 506: 'gives',
 507: 'hes',
 508: 'wisdom',
 509: 'desire',
 510: 'carry',
 511: 'gets',
 512: 'sea',
 513: 'waste',
 514: 'bear',
 515: 'father',
 516: 'girls',
 517: 'act',
 518: 'fool',
 519: 'persons',
 520: 'control',
 521: 'finally',
 522: 'apart',
 523: 'special',
 524: 'quite',
 525: 'stronger',
 526: 'imagine',
 527: 'name',
 528: 'hurts',
 529: 'minds',
 530: 'under',
 531: 'teach',
 532: 'school',
 533: 'nice',
 534: 'touch',
 535: 'wake',
 536: 'tree',
 537: 'morning',
 538: 'mine',
 539: 'ten',
 540: 'called',
 541: 'came',
 542: 'seek',
 543: 'weve',
 544: 'sense',
 545: 'getting',
 546: 'kiss',
 547: 'writing',
 548: 'needs',
 549: 'deserve',
 550: 'dance',
 551: 'front',
 552: 'greatest',
 553: 'memories',
 554: 'sky',
 555: 'joy',
 556: 'feet',
 557: 'used',
 558: 'nor',
 559: 'value',
 560: 'age',
 561: 'longer',
 562: 'wouldnt',
 563: 'certain',
 564: 'okay',
 565: 'spend',
 566: 'run',
 567: 'clary',
 568: 'arms',
 569: 'merely',
 570: 'hearts',
 571: 'blood',
 572: 'short',
 573: 'met',
 574: 'shes',
 575: 'miss',
 576: 'simply',
 577: 'thinks',
 578: 'intelligent',
 579: 'oh',
 580: 'wrote',
 581: 'brave',
 582: 'whom',
 583: 'written',
 584: 'can’t',
 585: 'cry',
 586: 'feelings',
 587: 'storm',
 588: 'anybody',
 589: 'poetry',
 590: 'wonder',
 591: 'powerful',
 592: 'magic',
 593: 'gave',
 594: 'guy',
 595: 'step',
 596: 'burn',
 597: 'moon',
 598: 'escape',
 599: 'passion',
 600: 'trees',
 601: 'pleasure',
 602: 'matters',
 603: 'fantasy',
 604: 'necessary',
 605: 'faith',
 606: 'late',
 607: 'leaves',
 608: 'drink',
 609: 'avoid',
 610: 'above',
 611: 'heard',
 612: 'along',
 613: 'travel',
 614: 'infinite',
 615: 'throw',
 616: 'library',
 617: 'questions',
 618: 'looks',
 619: 'usually',
 620: 'holding',
 621: 'youd',
 622: 'instead',
 623: 'poor',
 624: 'memory',
 625: 'hour',
 626: 'grief',
 627: 'meaning',
 628: 'becomes',
 629: 'hide',
 630: 'saw',
 631: 'weak',
 632: 'falling',
 633: 'sex',
 634: 'almost',
 635: 'play',
 636: 'shut',
 637: 'cool',
 638: 'genius',
 639: 'hot',
 640: 'deal',
 641: 'minute',
 642: 'places',
 643: 'dies',
 644: 'probably',
 645: 'coming',
 646: 'painful',
 647: 'skin',
 648: 'heaven',
 649: 'accept',
 650: 'you’ve',
 651: 'build',
 652: 'song',
 653: 'laughter',
 654: 'didn’t',
 655: 'bring',
 656: 'wind',
 657: 'remain',
 658: 'none',
 659: 'common',
 660: 'move',
 661: 'nature',
 662: 'purpose',
 663: 'money',
 664: 'waiting',
 665: 'except',
 666: 'air',
 667: 'kids',
 668: 'beyond',
 669: 'losing',
 670: 'middle',
 671: 'evil',
 672: 'tears',
 673: 'follow',
 674: 'running',
 675: 'went',
 676: 'sweet',
 677: 'bed',
 678: 'gods',
 679: 'they’re',
 680: 'لا',
 681: 'و',
 682: 'absolutely',
 683: 'fail',
 684: 'asleep',
 685: 'fairy',
 686: 'tales',
 687: 'large',
 688: 'angel',
 689: 'ready',
 690: 'tried',
 691: 'therefore',
 692: 'worst',
 693: 'mans',
 694: 'forward',
 695: 'wonderful',
 696: 'worry',
 697: 'that’s',
 698: 'present',
 699: 'forgotten',
 700: 'space',
 701: 'dying',
 702: 'whether',
 703: 'rain',
 704: 'amazing',
 705: 'road',
 706: 'count',
 707: 'kindness',
 708: 'eat',
 709: 'wasnt',
 710: 'white',
 711: 'reach',
 712: 'mouth',
 713: '“the',
 714: 'ways',
 715: '“i',
 716: 'judge',
 717: 'eye',
 718: 'sin',
 719: 'soon',
 720: 'spirit',
 721: 'across',
 722: 'lord',
 723: 'terrible',
 724: 'taken',
 725: 'silent',
 726: 'outside',
 727: 'greater',
 728: 'idea',
 729: 'humans',
 730: 'moving',
 731: 'hours',
 732: 'strange',
 733: 'education',
 734: 'sight',
 735: 'learning',
 736: 'sing',
 737: 'begins',
 738: 'fun',
 739: 'fighting',
 740: 'religion',
 741: 'form',
 742: 'paper',
 743: 'crying',
 744: 'piece',
 745: 'window',
 746: 'among',
 747: 'leaving',
 748: 'cut',
 749: 'toward',
 750: 'moments',
 751: 'songs',
 752: 'changing',
 753: 'madness',
 754: 'mess',
 755: 'enemies',
 756: 'needed',
 757: 'unhappy',
 758: 'chest',
 759: 'angry',
 760: 'problem',
 761: 'order',
 762: 'safe',
 763: 'troubles',
 764: 'trouble',
 765: 'whenever',
 766: 'someday',
 767: 'mistake',
 768: 'path',
 769: 'difficult',
 770: 'discover',
 771: 'share',
 772: 'blue',
 773: 'fell',
 774: 'please',
 775: 'interesting',
 776: 'figure',
 777: 'failure',
 778: 'hundred',
 779: 'wounds',
 780: 'given',
 781: 'fly',
 782: 'turned',
 783: 'pretend',
 784: 'telling',
 785: 'giving',
 786: 'stood',
 787: 'watch',
 788: 'glass',
 789: 'summer',
 790: 'hates',
 791: 'food',
 792: 'lips',
 793: 'protect',
 794: 'started',
 795: 'havent',
 796: 'ability',
 797: 'easier',
 798: 'ideas',
 799: 'rare',
 800: 'kissed',
 801: 'fill',
 802: 'opinion',
 803: 'instant',
 804: 'soft',
 805: 'depends',
 806: 'هو',
 807: 'sort',
 808: 'أن',
 809: 'changed',
 810: 'tea',
 811: 'anyway',
 812: 'baby',
 813: 'smiling',
 814: 'brain',
 815: 'opposite',
 816: 'indifference',
 817: 'problems',
 818: 'case',
 819: 'cup',
 820: 'attempt',
 821: 'doubt',
 822: 'ahead',
 823: 'flower',
 824: 'characters',
 825: 'rules',
 826: 'chance',
 827: 'boring',
 828: 'dragons',
 829: 'risk',
 830: 'gift',
 831: 'deeply',
 832: 'adventure',
 833: 'walls',
 834: 'guess',
 835: 'clothes',
 836: 'glory',
 837: 'taught',
 838: 'he’s',
 839: 'bird',
 840: 'fig',
 841: 'wear',
 842: 'destroy',
 843: 'actions',
 844: 'magnus',
 845: 'floor',
 846: 'hair',
 847: 'survive',
 848: 'fingers',
 849: 'force',
 850: 'ron',
 851: 'goodbye',
 852: 'rule',
 853: 'families',
 854: 'understanding',
 855: 'self',
 856: 'capable',
 857: 'fox',
 858: 'stuff',
 859: 'herself',
 860: 'burning',
 861: 'spring',
 862: 'naked',
 863: 'sorrow',
 864: 'doesn’t',
 865: 'country',
 866: 'wanting',
 867: 'talking',
 868: 'tells',
 869: 'من',
 870: 'chamber',
 871: 'choices',
 872: 'lifes',
 873: 'bravery',
 874: 'nonsense',
 875: 'lack',
 876: 'conscience',
 877: 'pride',
 878: 'reader',
 879: 'reads',
 880: 'lover',
 881: 'horrible',
 882: 'belief',
 883: 'fully',
 884: 'dumbledore',
 885: 'constantly',
 886: 'kept',
 887: 'allow',
 888: 'gold',
 889: 'car',
 890: 'cats',
 891: 'blind',
 892: 'bit',
 893: 'bigger',
 894: 'you’ll',
 895: 'sound',
 896: '2',
 897: 'deepest',
 898: 'warm',
 899: 'writer',
 900: 'greatness',
 901: 'science',
 902: 'character',
 903: 'believed',
 904: 'lucky',
 905: 'awful',
 906: 'job',
 907: 'sorry',
 908: 'hidden',
 909: 'cold',
 910: 'opinions',
 911: 'easily',
 912: 'somehow',
 913: 'complete',
 914: 'relationship',
 915: 'surprise',
 916: 'wed',
 917: 'dangerous',
 918: 'promise',
 919: 'precisely',
 920: 'realized',
 921: 'offer',
 922: 'create',
 923: 'empty',
 924: 'wild',
 925: 'sadness',
 926: 'lets',
 927: 'neither',
 928: 'hit',
 929: 'killed',
 930: 'peeta',
 931: 'i’ve',
 932: 'enemy',
 933: 'feels',
 934: 'tired',
 935: 'teacher',
 936: 'corner',
 937: 'flowers',
 938: 'missing',
 939: 'parents',
 940: 'return',
 941: 'comfort',
 942: 'suddenly',
 943: 'depression',
 944: 'eternal',
 945: 'نصف',
 946: 'created',
 947: '“it',
 948: 'theyll',
 949: 'explain',
 950: 'six',
 951: 'cause',
 952: 'admit',
 953: 'onto',
 954: 'sitting',
 955: 'happening',
 956: 'staring',
 957: 'opened',
 958: 'possibly',
 959: 'whose',
 960: 'answers',
 961: 'drive',
 962: 'differently',
 963: 'ignore',
 964: 'quiet',
 965: 'clear',
 966: 'brings',
 967: 'mate',
 968: 'yesterday',
 969: 'till',
 970: 'dogs',
 971: 'dust',
 972: 'fallen',
 973: 'lead',
 974: 'fit',
 975: 'transform',
 976: 'tessa',
 977: 'pretending',
 978: 'taking',
 979: 'date',
 980: 'list',
 981: 'she’s',
 982: 'pages',
 983: 'likes',
 984: 'understood',
 985: 'favorite',
 986: 'breath',
 987: 'pure',
 988: 'filled',
 989: 'scars',
 990: 'ordinary',
 991: 'grateful',
 992: 'literature',
 993: 'sees',
 994: 'advice',
 995: 'parts',
 996: 'simon',
 997: 'faster',
 998: 'fine',
 999: 'fate',
 1000: 'ugly',
 ...}

In [50]:
seq=tok.texts_to_sequences(quotes)

In [51]:
type(tok.texts_to_sequences([['hello']]))

list

In [52]:
for i in range(3):
  print(quotes[i])

“the world as we have created it is a process of our thinking it cannot be changed without changing our thinking”
“it is our choices harry that show what we truly are far more than our abilities”
“there are only two ways to live your life one is as though nothing is a miracle the other is as though everything is a miracle”

In [53]:
for i in range(3):
  print(seq[i])

[713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145, 12, 809, 104, 752, 70, 2461]
[947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14, 294, 52, 54, 70, 3676]
[1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93, 7, 5, 1157, 1, 101, 7, 29, 329, 126, 7, 5, 3677]

In [54]:
X=[]
y=[]

In [55]:
for sq in seq:
  for i in range(1,len(sq)):
    input_seq=sq[:i]
    output_seq=sq[i]
    X.append(input_seq)
    y.append(output_seq)

In [56]:
len(X)

85270

In [57]:
len(y)

85270

In [58]:
maxLen=max(len(x) for x in X)
print(maxLen)

745

In [59]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
X_padded=pad_sequences(X,maxlen=maxLen,padding='pre')

In [60]:
y=np.array(y)

In [61]:
X_padded.shape

(85270, 745)

In [62]:
from tensorflow.keras.utils import to_categorical
y_one_hot=to_categorical(y,num_classes=vocab_size)

In [63]:
y_one_hot.shape

(85270, 8978)

In [28]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding , SimpleRNN, LSTM

In [29]:
embed_dim=50
rnn_units=128

In [30]:
rnn_model=Sequential()

In [31]:
rnn_model.add(
    Embedding(input_dim=vocab_size,output_dim=embed_dim,input_length=maxLen)
)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [32]:
rnn_model.add(SimpleRNN(units=rnn_units))
rnn_model.add(Dense(units=vocab_size,activation='softmax'))

In [33]:
rnn_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [34]:
rnn_model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [35]:
lstm_model=Sequential()
lstm_model.add(
    Embedding(input_dim=vocab_size,output_dim=embed_dim,input_length=maxLen)
)
lstm_model.add(LSTM(units=rnn_units))
lstm_model.add(Dense(units=vocab_size,activation='softmax'))

In [36]:
lstm_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [37]:
epochs=10
batch_size=128

In [ ]:
# history_rnn=rnn_model.fit(
#     X_padded,y_one_hot,
#     epochs=epochs,
#     batch_size=batch_size,
#     validation_split=0.1
# )

Epoch 1/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 48s 73ms/step - accuracy: 0.0476 - loss: 6.6812 - val_accuracy: 0.0665 - val_loss: 6.4689
Epoch 2/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 67ms/step - accuracy: 0.0828 - loss: 6.0619 - val_accuracy: 0.0908 - val_loss: 6.2995
Epoch 3/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 67ms/step - accuracy: 0.1032 - loss: 5.7228 - val_accuracy: 0.1032 - val_loss: 6.2603
Epoch 4/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 67ms/step - accuracy: 0.1187 - loss: 5.4343 - val_accuracy: 0.1067 - val_loss: 6.2846
Epoch 5/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 67ms/step - accuracy: 0.1313 - loss: 5.1799 - val_accuracy: 0.1104 - val_loss: 6.3358
Epoch 6/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 67ms/step - accuracy: 0.1451 - loss: 4.9421 - val_accuracy: 0.1134 - val_loss: 6.4004
Epoch 7/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 67ms/step - accuracy: 0.1615 - loss: 4.7188 - val_accuracy: 0.1120 - val_loss: 6.4502
Epoch 8/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 67ms/step - accuracy: 0.1785 - loss: 4.5099 - val_accuracy: 0.1098 - val_loss: 6.5242
Epoch 9/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 67ms/step - accuracy: 0.1988 - loss: 4.3113 - val_accuracy: 0.1105 - val_loss: 6.5966
Epoch 10/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 67ms/step - accuracy: 0.2217 - loss: 4.1243 - val_accuracy: 0.1060 - val_loss: 6.6938

In [ ]:
# epochs = 100
# batch_size = 128

# history_lstm = lstm_model.fit(
#     X_padded, y_one_hot,
#     epochs=epochs,
#     batch_size=batch_size,
#     validation_split=0.1
# )

Epoch 1/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 38s 54ms/step - accuracy: 0.0388 - loss: 6.7460 - val_accuracy: 0.0454 - val_loss: 6.6868
Epoch 2/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.0561 - loss: 6.3365 - val_accuracy: 0.0644 - val_loss: 6.5375
Epoch 3/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.0803 - loss: 6.0457 - val_accuracy: 0.0877 - val_loss: 6.4397
Epoch 4/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.0961 - loss: 5.8200 - val_accuracy: 0.0936 - val_loss: 6.4097
Epoch 5/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.1067 - loss: 5.6358 - val_accuracy: 0.1019 - val_loss: 6.3996
Epoch 6/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.1195 - loss: 5.4599 - val_accuracy: 0.1040 - val_loss: 6.4048
Epoch 7/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.1301 - loss: 5.2914 - val_accuracy: 0.1075 - val_loss: 6.4213
Epoch 8/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.1397 - loss: 5.1363 - val_accuracy: 0.1125 - val_loss: 6.4709
Epoch 9/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 54ms/step - accuracy: 0.1478 - loss: 4.9904 - val_accuracy: 0.1121 - val_loss: 6.4970
Epoch 10/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.1545 - loss: 4.8504 - val_accuracy: 0.1136 - val_loss: 6.5466
Epoch 11/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.1622 - loss: 4.7144 - val_accuracy: 0.1143 - val_loss: 6.5980
Epoch 12/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 54ms/step - accuracy: 0.1698 - loss: 4.5823 - val_accuracy: 0.1134 - val_loss: 6.6558
Epoch 13/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.1815 - loss: 4.4521 - val_accuracy: 0.1138 - val_loss: 6.7209
Epoch 14/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.1920 - loss: 4.3251 - val_accuracy: 0.1147 - val_loss: 6.7808
Epoch 15/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 54ms/step - accuracy: 0.2047 - loss: 4.2023 - val_accuracy: 0.1139 - val_loss: 6.8603
Epoch 16/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.2181 - loss: 4.0833 - val_accuracy: 0.1123 - val_loss: 6.9209
Epoch 17/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.2337 - loss: 3.9696 - val_accuracy: 0.1120 - val_loss: 7.0025
Epoch 18/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.2482 - loss: 3.8609 - val_accuracy: 0.1131 - val_loss: 7.0856
Epoch 19/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.2642 - loss: 3.7572 - val_accuracy: 0.1108 - val_loss: 7.1641
Epoch 20/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.2774 - loss: 3.6620 - val_accuracy: 0.1123 - val_loss: 7.2387
Epoch 21/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.2919 - loss: 3.5730 - val_accuracy: 0.1105 - val_loss: 7.3117
Epoch 22/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 53ms/step - accuracy: 0.3034 - loss: 3.4881 - val_accuracy: 0.1100 - val_loss: 7.4014
Epoch 23/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 53ms/step - accuracy: 0.3170 - loss: 3.4089 - val_accuracy: 0.1077 - val_loss: 7.4769
Epoch 24/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.3295 - loss: 3.3341 - val_accuracy: 0.1078 - val_loss: 7.5581
Epoch 25/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.3410 - loss: 3.2634 - val_accuracy: 0.1053 - val_loss: 7.6312
Epoch 26/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.3519 - loss: 3.1975 - val_accuracy: 0.1053 - val_loss: 7.6991
Epoch 27/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.3625 - loss: 3.1321 - val_accuracy: 0.1047 - val_loss: 7.7606
Epoch 28/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.3723 - loss: 3.0699 - val_accuracy: 0.1044 - val_loss: 7.8508
Epoch 29/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.3818 - loss: 3.0103 - val_accuracy: 0.1036 - val_loss: 7.9206
Epoch 30/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.3929 - loss: 2.9531 - val_accuracy: 0.1040 - val_loss: 7.9851
Epoch 31/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4023 - loss: 2.8989 - val_accuracy: 0.1023 - val_loss: 8.0510
Epoch 32/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4109 - loss: 2.8469 - val_accuracy: 0.1005 - val_loss: 8.1122
Epoch 33/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4193 - loss: 2.7929 - val_accuracy: 0.1005 - val_loss: 8.1890
Epoch 34/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4286 - loss: 2.7434 - val_accuracy: 0.0984 - val_loss: 8.2558
Epoch 35/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.4374 - loss: 2.6948 - val_accuracy: 0.1018 - val_loss: 8.3130
Epoch 36/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4451 - loss: 2.6476 - val_accuracy: 0.0969 - val_loss: 8.3826
Epoch 37/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4518 - loss: 2.6037 - val_accuracy: 0.0963 - val_loss: 8.4445
Epoch 38/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.4636 - loss: 2.5589 - val_accuracy: 0.0978 - val_loss: 8.5162
Epoch 39/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4689 - loss: 2.5157 - val_accuracy: 0.0962 - val_loss: 8.5781
Epoch 40/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4773 - loss: 2.4724 - val_accuracy: 0.0963 - val_loss: 8.6327
Epoch 41/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4836 - loss: 2.4332 - val_accuracy: 0.0972 - val_loss: 8.7053
Epoch 42/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 54ms/step - accuracy: 0.4914 - loss: 2.3924 - val_accuracy: 0.0965 - val_loss: 8.7610
Epoch 43/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4980 - loss: 2.3538 - val_accuracy: 0.0935 - val_loss: 8.8194
Epoch 44/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.5047 - loss: 2.3156 - val_accuracy: 0.0946 - val_loss: 8.8798
Epoch 45/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5124 - loss: 2.2785 - val_accuracy: 0.0966 - val_loss: 8.9420
Epoch 46/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.5202 - loss: 2.2441 - val_accuracy: 0.0941 - val_loss: 9.0003
Epoch 47/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.5265 - loss: 2.2076 - val_accuracy: 0.0919 - val_loss: 9.0565
Epoch 48/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 52ms/step - accuracy: 0.5319 - loss: 2.1756 - val_accuracy: 0.0921 - val_loss: 9.1235
Epoch 49/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 52ms/step - accuracy: 0.5383 - loss: 2.1419 - val_accuracy: 0.0926 - val_loss: 9.1856
Epoch 50/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 52ms/step - accuracy: 0.5452 - loss: 2.1078 - val_accuracy: 0.0903 - val_loss: 9.2592
Epoch 51/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 42s 54ms/step - accuracy: 0.5508 - loss: 2.0781 - val_accuracy: 0.0912 - val_loss: 9.3180
Epoch 52/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.5582 - loss: 2.0460 - val_accuracy: 0.0911 - val_loss: 9.3623
Epoch 53/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.5632 - loss: 2.0157 - val_accuracy: 0.0896 - val_loss: 9.4230
Epoch 54/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.5693 - loss: 1.9872 - val_accuracy: 0.0892 - val_loss: 9.4824
Epoch 55/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 53ms/step - accuracy: 0.5752 - loss: 1.9588 - val_accuracy: 0.0880 - val_loss: 9.5379
Epoch 56/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 52ms/step - accuracy: 0.5789 - loss: 1.9312 - val_accuracy: 0.0862 - val_loss: 9.6140
Epoch 57/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.5860 - loss: 1.9030 - val_accuracy: 0.0869 - val_loss: 9.6732
Epoch 58/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.5909 - loss: 1.8763 - val_accuracy: 0.0888 - val_loss: 9.7156
Epoch 59/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 52ms/step - accuracy: 0.5963 - loss: 1.8509 - val_accuracy: 0.0861 - val_loss: 9.7536
Epoch 60/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.6016 - loss: 1.8247 - val_accuracy: 0.0858 - val_loss: 9.8206
Epoch 61/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.6064 - loss: 1.7995 - val_accuracy: 0.0856 - val_loss: 9.8916
Epoch 62/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.6127 - loss: 1.7746 - val_accuracy: 0.0858 - val_loss: 9.9507
Epoch 63/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.6173 - loss: 1.7510 - val_accuracy: 0.0842 - val_loss: 10.0038
Epoch 64/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.6214 - loss: 1.7262 - val_accuracy: 0.0824 - val_loss: 10.0453
Epoch 65/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.6266 - loss: 1.7042 - val_accuracy: 0.0849 - val_loss: 10.1077
Epoch 66/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6312 - loss: 1.6813 - val_accuracy: 0.0860 - val_loss: 10.1653
Epoch 67/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6360 - loss: 1.6596 - val_accuracy: 0.0831 - val_loss: 10.2181
Epoch 68/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6413 - loss: 1.6372 - val_accuracy: 0.0839 - val_loss: 10.2869
Epoch 69/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.6438 - loss: 1.6160 - val_accuracy: 0.0829 - val_loss: 10.3384
Epoch 70/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6501 - loss: 1.5963 - val_accuracy: 0.0835 - val_loss: 10.3820
Epoch 71/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 53ms/step - accuracy: 0.6537 - loss: 1.5753 - val_accuracy: 0.0836 - val_loss: 10.4470
Epoch 72/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.6586 - loss: 1.5561 - val_accuracy: 0.0828 - val_loss: 10.5017
Epoch 73/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.6616 - loss: 1.5363 - val_accuracy: 0.0817 - val_loss: 10.5527
Epoch 74/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 42s 54ms/step - accuracy: 0.6660 - loss: 1.5191 - val_accuracy: 0.0819 - val_loss: 10.5993
Epoch 75/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 53ms/step - accuracy: 0.6703 - loss: 1.4988 - val_accuracy: 0.0812 - val_loss: 10.6507
Epoch 76/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 52ms/step - accuracy: 0.6740 - loss: 1.4801 - val_accuracy: 0.0816 - val_loss: 10.7071
Epoch 77/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.6780 - loss: 1.4628 - val_accuracy: 0.0795 - val_loss: 10.7494
Epoch 78/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 52ms/step - accuracy: 0.6808 - loss: 1.4469 - val_accuracy: 0.0797 - val_loss: 10.8277
Epoch 79/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.6856 - loss: 1.4282 - val_accuracy: 0.0805 - val_loss: 10.8636
Epoch 80/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 42s 54ms/step - accuracy: 0.6898 - loss: 1.4106 - val_accuracy: 0.0793 - val_loss: 10.9267
Epoch 81/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6921 - loss: 1.3942 - val_accuracy: 0.0786 - val_loss: 10.9667
Epoch 82/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.6964 - loss: 1.3794 - val_accuracy: 0.0795 - val_loss: 11.0167
Epoch 83/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.7001 - loss: 1.3627 - val_accuracy: 0.0772 - val_loss: 11.0625
Epoch 84/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.7032 - loss: 1.3466 - val_accuracy: 0.0803 - val_loss: 11.1186
Epoch 85/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.7075 - loss: 1.3316 - val_accuracy: 0.0790 - val_loss: 11.1715
Epoch 86/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 53ms/step - accuracy: 0.7101 - loss: 1.3150 - val_accuracy: 0.0793 - val_loss: 11.2163
Epoch 87/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 53ms/step - accuracy: 0.7134 - loss: 1.3009 - val_accuracy: 0.0799 - val_loss: 11.2721
Epoch 88/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.7163 - loss: 1.2873 - val_accuracy: 0.0786 - val_loss: 11.3217
Epoch 89/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.7203 - loss: 1.2726 - val_accuracy: 0.0787 - val_loss: 11.3784
Epoch 90/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.7217 - loss: 1.2588 - val_accuracy: 0.0787 - val_loss: 11.4236
Epoch 91/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.7246 - loss: 1.2457 - val_accuracy: 0.0773 - val_loss: 11.4390
Epoch 92/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.7284 - loss: 1.2319 - val_accuracy: 0.0783 - val_loss: 11.5066
Epoch 93/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 42s 54ms/step - accuracy: 0.7305 - loss: 1.2190 - val_accuracy: 0.0772 - val_loss: 11.5768
Epoch 94/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.7333 - loss: 1.2045 - val_accuracy: 0.0774 - val_loss: 11.6048
Epoch 95/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.7359 - loss: 1.1941 - val_accuracy: 0.0779 - val_loss: 11.6662
Epoch 96/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.7394 - loss: 1.1809 - val_accuracy: 0.0754 - val_loss: 11.7077
Epoch 97/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.7415 - loss: 1.1698 - val_accuracy: 0.0765 - val_loss: 11.7675
Epoch 98/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.7452 - loss: 1.1562 - val_accuracy: 0.0774 - val_loss: 11.8114
Epoch 99/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.7467 - loss: 1.1429 - val_accuracy: 0.0767 - val_loss: 11.8555
Epoch 100/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 53ms/step - accuracy: 0.7496 - loss: 1.1325 - val_accuracy: 0.0758 - val_loss: 11.9049

In [40]:
lstm_model.save('lstm_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [32]:
from tensorflow.keras.models import load_model
lstm_model=load_model('/content/lstm_model.h5')

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [33]:
index_to_word=tok.index_word
index_to_word

{1: 'the',
 2: 'you',
 3: 'to',
 4: 'and',
 5: 'a',
 6: 'i',
 7: 'is',
 8: 'of',
 9: 'that',
 10: 'it',
 11: 'in',
 12: 'be',
 13: 'not',
 14: 'are',
 15: 'your',
 16: 'have',
 17: 'for',
 18: 'but',
 19: 'we',
 20: 'if',
 21: 'what',
 22: 'with',
 23: 'all',
 24: 'love',
 25: 'can',
 26: 'my',
 27: 'when',
 28: 'will',
 29: 'as',
 30: 'who',
 31: 'do',
 32: 'or',
 33: 'me',
 34: 'he',
 35: 'they',
 36: 'life',
 37: 'one',
 38: 'was',
 39: 'like',
 40: 'there',
 41: 'people',
 42: 'on',
 43: 'its',
 44: 'at',
 45: 'so',
 46: 'never',
 47: 'no',
 48: 'them',
 49: 'dont',
 50: 'know',
 51: 'just',
 52: 'more',
 53: 'only',
 54: 'than',
 55: 'because',
 56: 'this',
 57: 'want',
 58: 'up',
 59: 'how',
 60: 'his',
 61: 'things',
 62: 'world',
 63: 'by',
 64: 'think',
 65: 'make',
 66: 'about',
 67: 'time',
 68: 'from',
 69: 'always',
 70: 'our',
 71: 'an',
 72: 'out',
 73: 'us',
 74: 'good',
 75: 'said',
 76: 'she',
 77: 'her',
 78: 'way',
 79: 'go',
 80: 'am',
 81: 'live',
 82: 'has',
 83: 'something',
 84: 'see',
 85: 'too',
 86: 'then',
 87: 'every',
 88: 'were',
 89: 'some',
 90: 'man',
 91: 'thing',
 92: 'heart',
 93: 'nothing',
 94: 'get',
 95: 'him',
 96: 'youre',
 97: 'would',
 98: 'those',
 99: 'their',
 100: 'yourself',
 101: 'other',
 102: 'let',
 103: 'into',
 104: 'without',
 105: 'much',
 106: 'im',
 107: 'could',
 108: 'had',
 109: 'someone',
 110: 'ever',
 111: 'day',
 112: 'even',
 113: 'find',
 114: 'books',
 115: 'right',
 116: 'person',
 117: 'most',
 118: 'say',
 119: 'must',
 120: 'which',
 121: 'been',
 122: 'own',
 123: 'sometimes',
 124: 'read',
 125: 'should',
 126: 'everything',
 127: 'believe',
 128: 'being',
 129: 'really',
 130: 'going',
 131: 'feel',
 132: 'come',
 133: 'give',
 134: 'may',
 135: 'where',
 136: 'book',
 137: 'thats',
 138: 'tell',
 139: 'little',
 140: 'cant',
 141: 'back',
 142: 'words',
 143: 'over',
 144: 'better',
 145: 'cannot',
 146: 'through',
 147: 'now',
 148: 'any',
 149: 'enough',
 150: 'does',
 151: 'great',
 152: 'god',
 153: 'look',
 154: 'anything',
 155: 'change',
 156: 'another',
 157: 'many',
 158: 'remember',
 159: 'best',
 160: 'down',
 161: 'true',
 162: 'still',
 163: 'did',
 164: 'need',
 165: 'mind',
 166: 'soul',
 167: 'well',
 168: 'until',
 169: 'each',
 170: 'again',
 171: 'else',
 172: 'why',
 173: 'long',
 174: 'truth',
 175: 'loved',
 176: 'keep',
 177: 'very',
 178: 'first',
 179: 'moment',
 180: 'woman',
 181: 'matter',
 182: 'doesnt',
 183: 'before',
 184: 'men',
 185: 'others',
 186: 'once',
 187: 'human',
 188: 'fear',
 189: 'end',
 190: 'around',
 191: 'ive',
 192: 'beautiful',
 193: 'happy',
 194: 'kind',
 195: 'don’t',
 196: 'die',
 197: 'girl',
 198: 'happiness',
 199: 'made',
 200: 'take',
 201: 'two',
 202: 'become',
 203: 'learn',
 204: 'myself',
 205: 'theres',
 206: 'got',
 207: 'hope',
 208: 'part',
 209: 'same',
 210: 'alone',
 211: 'pain',
 212: 'friends',
 213: 'makes',
 214: 'death',
 215: 'real',
 216: 'friend',
 217: 'inside',
 218: 'thought',
 219: 'after',
 220: 'years',
 221: 'here',
 222: 'eyes',
 223: 'wrong',
 224: 'understand',
 225: 'loves',
 226: 'lives',
 227: 'reading',
 228: 'fall',
 229: 'new',
 230: 'light',
 231: 'forever',
 232: 'while',
 233: 'dream',
 234: 'ones',
 235: 'everyone',
 236: 'living',
 237: 'youll',
 238: 'bad',
 239: 'lose',
 240: 'away',
 241: 'forget',
 242: 'shall',
 243: 'hard',
 244: 'upon',
 245: 'between',
 246: 'face',
 247: 'stop',
 248: 'write',
 249: 'dreams',
 250: 'off',
 251: 'future',
 252: 'whole',
 253: 'might',
 254: 'maybe',
 255: 'ourselves',
 256: 'hell',
 257: 'looking',
 258: 'stars',
 259: 'wanted',
 260: 'trying',
 261: 'old',
 262: 'last',
 263: 'isnt',
 264: 'courage',
 265: 'try',
 266: 'mean',
 267: 'together',
 268: 'doing',
 269: 'place',
 270: 'less',
 271: 'stay',
 272: 'theyre',
 273: 'hate',
 274: 'knows',
 275: 'earth',
 276: 'put',
 277: 'felt',
 278: 'times',
 279: 'rather',
 280: 'often',
 281: 'work',
 282: 'night',
 283: 'trust',
 284: 'grow',
 285: 'walk',
 286: 'says',
 287: 'saying',
 288: 'anyone',
 289: 'smile',
 290: 'hurt',
 291: 'story',
 292: 'listen',
 293: 'thinking',
 294: 'far',
 295: 'laugh',
 296: 'small',
 297: 'having',
 298: 'reality',
 299: 'means',
 300: 'women',
 301: 'sad',
 302: 'leave',
 303: 'these',
 304: 'head',
 305: 'music',
 306: 'i’m',
 307: 'youve',
 308: 'it’s',
 309: 'important',
 310: 'somebody',
 311: 'against',
 312: 'feeling',
 313: 'beauty',
 314: 'stand',
 315: 'hand',
 316: 'done',
 317: 'reason',
 318: 'universe',
 319: 'didnt',
 320: 'fire',
 321: 'told',
 322: 'strong',
 323: 'happens',
 324: 'sure',
 325: 'talk',
 326: 'word',
 327: 'himself',
 328: 'full',
 329: 'though',
 330: 'gone',
 331: 'worth',
 332: 'point',
 333: 'door',
 334: 'broken',
 335: 'dark',
 336: 'sit',
 337: 'wish',
 338: 'happen',
 339: 'you’re',
 340: 'least',
 341: 'past',
 342: 'comes',
 343: 'hold',
 344: 'takes',
 345: 'perfect',
 346: 'stupid',
 347: 'children',
 348: 'start',
 349: 'experience',
 350: 'power',
 351: 'yet',
 352: 'asked',
 353: 'realize',
 354: 'making',
 355: 'behind',
 356: 'left',
 357: 'wants',
 358: 'choose',
 359: 'lot',
 360: 'whatever',
 361: 'lost',
 362: 'looked',
 363: 'wont',
 364: 'knowing',
 365: 'few',
 366: 'lie',
 367: 'different',
 368: 'hear',
 369: 'afraid',
 370: 'jace',
 371: 'ask',
 372: 'home',
 373: 'harry',
 374: 'impossible',
 375: 'lies',
 376: 'open',
 377: 'easy',
 378: 'already',
 379: 'three',
 380: 'exist',
 381: 'such',
 382: 'possible',
 383: 'use',
 384: 'thoughts',
 385: 'within',
 386: 'days',
 387: '—',
 388: 'themselves',
 389: 'also',
 390: 'break',
 391: 'mistakes',
 392: 'loving',
 393: 'alive',
 394: 'next',
 395: 'happened',
 396: 'wait',
 397: 'side',
 398: 'both',
 399: 'ill',
 400: 'secret',
 401: 'deep',
 402: 'sleep',
 403: 'silence',
 404: 'either',
 405: 'suffering',
 406: 'tomorrow',
 407: 'call',
 408: 'strength',
 409: 'help',
 410: 'meant',
 411: 'knew',
 412: 'speak',
 413: 'itself',
 414: 'seen',
 415: 'found',
 416: 'pretty',
 417: 'half',
 418: 'goes',
 419: 'high',
 420: 'lived',
 421: 'darkness',
 422: 'yours',
 423: 'choice',
 424: 'forgive',
 425: 'respect',
 426: 'young',
 427: 'simple',
 428: 'close',
 429: 'kill',
 430: 'beginning',
 431: 'whats',
 432: 'perhaps',
 433: 'show',
 434: 'success',
 435: 'arent',
 436: 'mad',
 437: 'friendship',
 438: 'thousand',
 439: 'crazy',
 440: 'house',
 441: 'nobody',
 442: 'history',
 443: 'able',
 444: 'set',
 445: 'meet',
 446: 'hands',
 447: 'rest',
 448: 'answer',
 449: 'id',
 450: 'voice',
 451: 'dare',
 452: 'second',
 453: 'expect',
 454: 'war',
 455: 'free',
 456: 'room',
 457: 'seems',
 458: 'somewhere',
 459: 'care',
 460: 'couldnt',
 461: 'fight',
 462: 'known',
 463: 'lonely',
 464: 'family',
 465: 'truly',
 466: 'decide',
 467: 'year',
 468: 'black',
 469: 'unless',
 470: 'begin',
 471: 'turn',
 472: 'sun',
 473: 'body',
 474: 'today',
 475: 'enjoy',
 476: 'child',
 477: 'fact',
 478: 'worse',
 479: 'yes',
 480: 'freedom',
 481: 'mother',
 482: 'actually',
 483: 'course',
 484: 'born',
 485: 'seem',
 486: 'difference',
 487: 'dead',
 488: 'taste',
 489: 'everybody',
 490: 'peace',
 491: 'took',
 492: '–',
 493: 'stories',
 494: 'loneliness',
 495: 'art',
 496: 'imagination',
 497: 'wise',
 498: 'big',
 499: 'question',
 500: 'boy',
 501: 'learned',
 502: 'single',
 503: 'completely',
 504: 'water',
 505: 'knowledge',
 506: 'gives',
 507: 'hes',
 508: 'wisdom',
 509: 'desire',
 510: 'carry',
 511: 'gets',
 512: 'sea',
 513: 'waste',
 514: 'bear',
 515: 'father',
 516: 'girls',
 517: 'act',
 518: 'fool',
 519: 'persons',
 520: 'control',
 521: 'finally',
 522: 'apart',
 523: 'special',
 524: 'quite',
 525: 'stronger',
 526: 'imagine',
 527: 'name',
 528: 'hurts',
 529: 'minds',
 530: 'under',
 531: 'teach',
 532: 'school',
 533: 'nice',
 534: 'touch',
 535: 'wake',
 536: 'tree',
 537: 'morning',
 538: 'mine',
 539: 'ten',
 540: 'called',
 541: 'came',
 542: 'seek',
 543: 'weve',
 544: 'sense',
 545: 'getting',
 546: 'kiss',
 547: 'writing',
 548: 'needs',
 549: 'deserve',
 550: 'dance',
 551: 'front',
 552: 'greatest',
 553: 'memories',
 554: 'sky',
 555: 'joy',
 556: 'feet',
 557: 'used',
 558: 'nor',
 559: 'value',
 560: 'age',
 561: 'longer',
 562: 'wouldnt',
 563: 'certain',
 564: 'okay',
 565: 'spend',
 566: 'run',
 567: 'clary',
 568: 'arms',
 569: 'merely',
 570: 'hearts',
 571: 'blood',
 572: 'short',
 573: 'met',
 574: 'shes',
 575: 'miss',
 576: 'simply',
 577: 'thinks',
 578: 'intelligent',
 579: 'oh',
 580: 'wrote',
 581: 'brave',
 582: 'whom',
 583: 'written',
 584: 'can’t',
 585: 'cry',
 586: 'feelings',
 587: 'storm',
 588: 'anybody',
 589: 'poetry',
 590: 'wonder',
 591: 'powerful',
 592: 'magic',
 593: 'gave',
 594: 'guy',
 595: 'step',
 596: 'burn',
 597: 'moon',
 598: 'escape',
 599: 'passion',
 600: 'trees',
 601: 'pleasure',
 602: 'matters',
 603: 'fantasy',
 604: 'necessary',
 605: 'faith',
 606: 'late',
 607: 'leaves',
 608: 'drink',
 609: 'avoid',
 610: 'above',
 611: 'heard',
 612: 'along',
 613: 'travel',
 614: 'infinite',
 615: 'throw',
 616: 'library',
 617: 'questions',
 618: 'looks',
 619: 'usually',
 620: 'holding',
 621: 'youd',
 622: 'instead',
 623: 'poor',
 624: 'memory',
 625: 'hour',
 626: 'grief',
 627: 'meaning',
 628: 'becomes',
 629: 'hide',
 630: 'saw',
 631: 'weak',
 632: 'falling',
 633: 'sex',
 634: 'almost',
 635: 'play',
 636: 'shut',
 637: 'cool',
 638: 'genius',
 639: 'hot',
 640: 'deal',
 641: 'minute',
 642: 'places',
 643: 'dies',
 644: 'probably',
 645: 'coming',
 646: 'painful',
 647: 'skin',
 648: 'heaven',
 649: 'accept',
 650: 'you’ve',
 651: 'build',
 652: 'song',
 653: 'laughter',
 654: 'didn’t',
 655: 'bring',
 656: 'wind',
 657: 'remain',
 658: 'none',
 659: 'common',
 660: 'move',
 661: 'nature',
 662: 'purpose',
 663: 'money',
 664: 'waiting',
 665: 'except',
 666: 'air',
 667: 'kids',
 668: 'beyond',
 669: 'losing',
 670: 'middle',
 671: 'evil',
 672: 'tears',
 673: 'follow',
 674: 'running',
 675: 'went',
 676: 'sweet',
 677: 'bed',
 678: 'gods',
 679: 'they’re',
 680: 'لا',
 681: 'و',
 682: 'absolutely',
 683: 'fail',
 684: 'asleep',
 685: 'fairy',
 686: 'tales',
 687: 'large',
 688: 'angel',
 689: 'ready',
 690: 'tried',
 691: 'therefore',
 692: 'worst',
 693: 'mans',
 694: 'forward',
 695: 'wonderful',
 696: 'worry',
 697: 'that’s',
 698: 'present',
 699: 'forgotten',
 700: 'space',
 701: 'dying',
 702: 'whether',
 703: 'rain',
 704: 'amazing',
 705: 'road',
 706: 'count',
 707: 'kindness',
 708: 'eat',
 709: 'wasnt',
 710: 'white',
 711: 'reach',
 712: 'mouth',
 713: '“the',
 714: 'ways',
 715: '“i',
 716: 'judge',
 717: 'eye',
 718: 'sin',
 719: 'soon',
 720: 'spirit',
 721: 'across',
 722: 'lord',
 723: 'terrible',
 724: 'taken',
 725: 'silent',
 726: 'outside',
 727: 'greater',
 728: 'idea',
 729: 'humans',
 730: 'moving',
 731: 'hours',
 732: 'strange',
 733: 'education',
 734: 'sight',
 735: 'learning',
 736: 'sing',
 737: 'begins',
 738: 'fun',
 739: 'fighting',
 740: 'religion',
 741: 'form',
 742: 'paper',
 743: 'crying',
 744: 'piece',
 745: 'window',
 746: 'among',
 747: 'leaving',
 748: 'cut',
 749: 'toward',
 750: 'moments',
 751: 'songs',
 752: 'changing',
 753: 'madness',
 754: 'mess',
 755: 'enemies',
 756: 'needed',
 757: 'unhappy',
 758: 'chest',
 759: 'angry',
 760: 'problem',
 761: 'order',
 762: 'safe',
 763: 'troubles',
 764: 'trouble',
 765: 'whenever',
 766: 'someday',
 767: 'mistake',
 768: 'path',
 769: 'difficult',
 770: 'discover',
 771: 'share',
 772: 'blue',
 773: 'fell',
 774: 'please',
 775: 'interesting',
 776: 'figure',
 777: 'failure',
 778: 'hundred',
 779: 'wounds',
 780: 'given',
 781: 'fly',
 782: 'turned',
 783: 'pretend',
 784: 'telling',
 785: 'giving',
 786: 'stood',
 787: 'watch',
 788: 'glass',
 789: 'summer',
 790: 'hates',
 791: 'food',
 792: 'lips',
 793: 'protect',
 794: 'started',
 795: 'havent',
 796: 'ability',
 797: 'easier',
 798: 'ideas',
 799: 'rare',
 800: 'kissed',
 801: 'fill',
 802: 'opinion',
 803: 'instant',
 804: 'soft',
 805: 'depends',
 806: 'هو',
 807: 'sort',
 808: 'أن',
 809: 'changed',
 810: 'tea',
 811: 'anyway',
 812: 'baby',
 813: 'smiling',
 814: 'brain',
 815: 'opposite',
 816: 'indifference',
 817: 'problems',
 818: 'case',
 819: 'cup',
 820: 'attempt',
 821: 'doubt',
 822: 'ahead',
 823: 'flower',
 824: 'characters',
 825: 'rules',
 826: 'chance',
 827: 'boring',
 828: 'dragons',
 829: 'risk',
 830: 'gift',
 831: 'deeply',
 832: 'adventure',
 833: 'walls',
 834: 'guess',
 835: 'clothes',
 836: 'glory',
 837: 'taught',
 838: 'he’s',
 839: 'bird',
 840: 'fig',
 841: 'wear',
 842: 'destroy',
 843: 'actions',
 844: 'magnus',
 845: 'floor',
 846: 'hair',
 847: 'survive',
 848: 'fingers',
 849: 'force',
 850: 'ron',
 851: 'goodbye',
 852: 'rule',
 853: 'families',
 854: 'understanding',
 855: 'self',
 856: 'capable',
 857: 'fox',
 858: 'stuff',
 859: 'herself',
 860: 'burning',
 861: 'spring',
 862: 'naked',
 863: 'sorrow',
 864: 'doesn’t',
 865: 'country',
 866: 'wanting',
 867: 'talking',
 868: 'tells',
 869: 'من',
 870: 'chamber',
 871: 'choices',
 872: 'lifes',
 873: 'bravery',
 874: 'nonsense',
 875: 'lack',
 876: 'conscience',
 877: 'pride',
 878: 'reader',
 879: 'reads',
 880: 'lover',
 881: 'horrible',
 882: 'belief',
 883: 'fully',
 884: 'dumbledore',
 885: 'constantly',
 886: 'kept',
 887: 'allow',
 888: 'gold',
 889: 'car',
 890: 'cats',
 891: 'blind',
 892: 'bit',
 893: 'bigger',
 894: 'you’ll',
 895: 'sound',
 896: '2',
 897: 'deepest',
 898: 'warm',
 899: 'writer',
 900: 'greatness',
 901: 'science',
 902: 'character',
 903: 'believed',
 904: 'lucky',
 905: 'awful',
 906: 'job',
 907: 'sorry',
 908: 'hidden',
 909: 'cold',
 910: 'opinions',
 911: 'easily',
 912: 'somehow',
 913: 'complete',
 914: 'relationship',
 915: 'surprise',
 916: 'wed',
 917: 'dangerous',
 918: 'promise',
 919: 'precisely',
 920: 'realized',
 921: 'offer',
 922: 'create',
 923: 'empty',
 924: 'wild',
 925: 'sadness',
 926: 'lets',
 927: 'neither',
 928: 'hit',
 929: 'killed',
 930: 'peeta',
 931: 'i’ve',
 932: 'enemy',
 933: 'feels',
 934: 'tired',
 935: 'teacher',
 936: 'corner',
 937: 'flowers',
 938: 'missing',
 939: 'parents',
 940: 'return',
 941: 'comfort',
 942: 'suddenly',
 943: 'depression',
 944: 'eternal',
 945: 'نصف',
 946: 'created',
 947: '“it',
 948: 'theyll',
 949: 'explain',
 950: 'six',
 951: 'cause',
 952: 'admit',
 953: 'onto',
 954: 'sitting',
 955: 'happening',
 956: 'staring',
 957: 'opened',
 958: 'possibly',
 959: 'whose',
 960: 'answers',
 961: 'drive',
 962: 'differently',
 963: 'ignore',
 964: 'quiet',
 965: 'clear',
 966: 'brings',
 967: 'mate',
 968: 'yesterday',
 969: 'till',
 970: 'dogs',
 971: 'dust',
 972: 'fallen',
 973: 'lead',
 974: 'fit',
 975: 'transform',
 976: 'tessa',
 977: 'pretending',
 978: 'taking',
 979: 'date',
 980: 'list',
 981: 'she’s',
 982: 'pages',
 983: 'likes',
 984: 'understood',
 985: 'favorite',
 986: 'breath',
 987: 'pure',
 988: 'filled',
 989: 'scars',
 990: 'ordinary',
 991: 'grateful',
 992: 'literature',
 993: 'sees',
 994: 'advice',
 995: 'parts',
 996: 'simon',
 997: 'faster',
 998: 'fine',
 999: 'fate',
 1000: 'ugly',
 ...}

In [64]:
def predictor(model,tok,text,maxlen):
  text=text.lower()

  seq=tok.texts_to_sequences([text])[0]
  seq=pad_sequences([seq],maxlen=maxlen,padding='pre')

  pred=model.predict(seq,verbose=0)
  pred_word=index_to_word[np.argmax(pred)]

  return pred_word

In [65]:
seed_text="life is"
next_word=predictor(lstm_model,tok,seed_text,maxLen)
print(next_word)

not

In [66]:
def generate_text(model,tok,seed_text,maxLen,n_words):
  for _ in range(n_words):
    next_word=predictor(model,tok,seed_text,maxLen)
    if next_word == "":
      break
    seed_text += " " + next_word

  return seed_text

In [67]:
seed="the meaning of life"
generated_text=generate_text(lstm_model,tok,seed,maxLen,5)

In [68]:
generated_text

'the meaning of life is akin to choosing immobility'

In [69]:
import pickle
with open('tokenizer.pkl','wb') as f :
  pickle.dump(tok,f)

# joblib.dump('tokenizer.pkl') works same

In [70]:
with open('max_len.pkl','wb') as f:
  pickle.dump(maxLen,f)